-- Create sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id UUID NOT NULL PRIMARY KEY,
    user_id UUID NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    media_url VARCHAR(500) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    duration_seconds INTEGER,
    file_size_bytes BIGINT,
    mime_type VARCHAR(100),
    processing_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    processing_error VARCHAR(500),
    is_public BOOLEAN DEFAULT FALSE,
    view_count BIGINT DEFAULT 0,
    like_count BIGINT DEFAULT 0,
    comment_count BIGINT DEFAULT 0,
    reading_room_id UUID,
    transcript TEXT,
    tags VARCHAR(500),
    thumbnail_url VARCHAR(500),
    book_title VARCHAR(200),
    language VARCHAR(50),
    is_live BOOLEAN DEFAULT FALSE,
    author_name VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(255) NOT NULL DEFAULT 'anonymousUser',
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(255),
    deleted_reason VARCHAR(255),
    version SMALLINT NOT NULL DEFAULT 0
);