package org.readtogether.notification.common.enums;

public enum NotificationType {
    SESSION_UPLOAD_STARTED,
    SESSION_UPLOAD_PROGRESS,
    SESSION_UPLOAD_COMPLETED,
    SESSION_UPLOAD_FAILED,
    SESSION_PROCESSING_STARTED,
    SESSION_PROCESSING_COMPLETED,
    SESSION_PROCESSING_FAILED,
    GENERAL_INFO,
    SYSTEM_ALERT
}
